version: '2'
services:
  server:
    build: './api'
    ports:
      - 5000:5000
  telegram_bot:
    build: './client'
    ports:
      - 12341:12341
  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - 8545:8545
